use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/XXCommonTools/XXRepos.git'

target 'XXNetwork_Example' do
    
  pod 'XXNetwork', :path => '../'

  target 'XXNetwork_Tests' do
    inherit! :search_paths

    
  end
end
